# Generated by Django 5.0.7 on 2024-08-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resturant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RestaurentId', models.CharField(max_length=100)),
                ('RestaurentName', models.CharField(max_length=100)),
                ('RestaurentEmail', models.CharField(max_length=100)),
                ('RestaurentAddress', models.CharField(max_length=100)),
                ('RestaurentPhone', models.CharField(max_length=100)),
                ('RestaurentServices', models.CharField(max_length=100)),
            ],
        ),
    ]
